### PR TITLE
Make sure not to read and write the same file in the same pipeline.

### PR DESCRIPTION
**Pull request by BenJule**
In auto_setup_twrp_build_environment.sh line 120:
md5sum -t recovery.tar >> recovery.tar
----------^-- [SC2094](https://github.com/koalaman/shellcheck/wiki/SC2094): Make sure not to read and write the same file in the same pipeline.
----------------^-- [SC2094](https://github.com/koalaman/shellcheck/wiki/SC2094): Make sure not to read and write the same file in the same pipeline.

### CODE REVIEW

**Review by Mitsch79 — CHANGES_REQUESTED** [review]
md5sum -t recovery.tar >> tmp.tar && mv tmp.tar recovery.tar.md5

i guess this is not what we want :) 

This statement creates an md5 sum of the tar file and writes it to tmp.tar. Then it renames tmp.tar to recovery.tar.md5. This results in a text file only including the md5sum.

What the original statement does ist creating the md5 sum and adding it to the end of the tar file (e.g. tar ball) itself as additional data. Odin reads out this extra data and verifies the files integrity.

So i'd suggest reverting this commit.

**Review by Mitsch79 — APPROVED** [review]
Thanks :+1:

**Review by Mitsch79 — COMMENTED** [review]
What does the array do?

**Comment by BenJule** [comment]
Exception handling?

**Review by Mitsch79 — COMMENTED** [review]
Btw, the original statement does not read and write in the same pipeline.
This only applies if you have something like (pseudo code)

read file | write file >> pipe to file

In this case it will not work as expected.
In our case we have

create md5sum >> pipe at the end of file. Meaning there's no file modification inside the pipe.

**Comment by BenJule** [comment]
Upps thy for clarification.

**Comment by Mitsch79** [comment]
What kind of exception is the array handling, i mean 

make -j9 recoveryimage 

doesn't seem to cause exceptions, or does it?

I was actually thinking whether we could find out the number of existing cores/threads an set it automatically.

**Review by Mitsch79 — APPROVED** [review]

**Review by Mitsch79 — APPROVED** [review]

**Pull request merged**
